import DocsLayout from '@/layouts/DocsLayout';
import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootDocsLayout = ({
  children,
}: Readonly<{ children: React.ReactNode }>) => <DocsLayout>{children}</DocsLayout>

export default RootDocsLayout;
