import { Blocks, Book, Code, Terminal } from 'lucide-react';
import type { Metadata } from 'next';
import Link from 'next/link';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const navigationItems = [
  {
    title: "Getting Started",
    items: [
      {
        title: "Introduction",
        href: "docs/introduction",
        icon: Book,
      },
      {
        title: "Installation",
        href: "docs/installation",
        icon: Terminal,
      },
    ],
  },
  {
    title: "Usage",
    items: [
      {
        title: "Component Usage",
        href: "docs/component-usage",
        icon: Code,
      },
      {
        title: "Composable Usage",
        href: "docs+6/composable-usage",
        icon: Blocks,
      },
    ],
  },
];


const DocsLayout = ({
  children,
}: Readonly<{ children: React.ReactNode }>) => {
  return (
    <div className='container mx-auto'>
      <div className="flex min-h-screen w-full bg-gradient-to-b from-white to-gray-50">
        <aside>
          <ul>
            {navigationItems.map(items => (items.items.map(item=> (<li key={item.href}>
              <Link href={item.href}>{item.title}</Link>
            </li>))))}
          </ul>

        </aside>
        <main className="flex-1 overflow-auto">
          <div className="animate-fade-up">
            {children}
          </div>
        </main>
      </div>
    </div>
  );
};

export default DocsLayout;
